[project]
name = "diver"
version = "0.1.0"
description = "divar diver is an alert service for notifying new listings on divar.ir"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.4",
]
